version: '3.7'

services:
  app:
    build: ./app
    container_name: app
    restart: always
    expose:
      - 8000
    env_file: .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: shop
      POSTGRES_HOST: db
    volumes:
      - type: 'bind'
        source: './volumes/app'
        target: '/app'
    depends_on:
      - db
      - nginx

  db:
    image: postgres:alpine
    container_name: postgres
    restart: always
    expose:
      - 5432
    volumes:
      - type: 'bind'
        source: './volumes/db'
        target: '/var/lib/postgresql/data'
    env_file: .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: shop

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - type: 'bind'
        source: './volumes/media'
        target: '/app/media'
      - type: 'bind'
        source: './volumes/static'
        target: '/app/static'
